services:
  - type: web
    name: farmwise
    runtime: python
    pythonVersion: 3.11
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"
    startCommand: "gunicorn farmwise.wsgi:application --bind 0.0.0.0:8000 --workers 4 --worker-class sync"
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: farmwise_db
    databaseName: farmwise
    plan: free
