services:
  - type: web
    name: farmwise
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear"
    startCommand: "bash start.sh"
    plans: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: OPENAI_API_KEY
        fromBuild: true
      - key: OPENWEATHER_API_KEY
        fromBuild: true
      - key: WEATHER_API_KEY
        fromBuild: true
      - key: GOOGLE_VISION_API_KEY
        fromBuild: true
      - key: SENDGRID_API_KEY
        fromBuild: true

databases:
  - name: farmwise_db
    databaseName: farmwise
    plan: free
