# Generated by Django 6.0.3 on 2026-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/products/'),
        ),
    ]
