# Generated by Django 6.0.3 on 2026-04-04 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productlisting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +254712345678 or 0712345678)', regex='^[0-9+\\-\\s()]{9,}$')]),
        ),
    ]
