# Generated by Django 6.0.3 on 2026-04-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rbac_user_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_coopera_cdaea1_idx',
            old_name='users_cooperative_idx',
        ),
    ]
