# Generated by Django 6.0.3 on 2026-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_users_cooperative_idx_users_coopera_cdaea1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestreport',
            name='organic_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
