# Generated by Django 5.2.10 on 2026-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_worker_skills_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/'),
        ),
    ]
