# Generated by Django 5.2.10 on 2026-04-08 07:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productlisting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_upload_path),
        ),
    ]
