# Generated by Django 5.2.10 on 2026-04-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productlisting_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('pressure', models.IntegerField(blank=True, help_text='Pressure in hPa', null=True)),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('cloudiness', models.IntegerField(blank=True, help_text='Cloud percentage', null=True)),
                ('condition', models.CharField(help_text='Weather condition (e.g., "Sunny", "Rainy")', max_length=100)),
                ('description', models.CharField(help_text='Detailed condition description', max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Weather icon code', max_length=50, null=True)),
                ('forecast_data', models.JSONField(default=dict, help_text='5-day forecast data')),
                ('location', models.CharField(help_text='Location name/coordinates', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='core.farm')),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'db_table': 'weather_data',
                'ordering': ['-last_updated'],
            },
        ),
    ]
