# Generated by Django 5.2.10 on 2026-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_weather_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, help_text='Animal photo (optional)', null=True, upload_to='livestock/animals/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='photo',
            field=models.ImageField(blank=True, help_text='Crop photo (optional)', null=True, upload_to='crops/plants/%Y/%m/'),
        ),
    ]
