# Generated by Django 5.2.10 on 2026-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_animal_photo_cropseason_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, help_text='Animal photo (optional)', null=True, upload_to='animals/'),
        ),
        migrations.AlterField(
            model_name='cropseason',
            name='photo',
            field=models.ImageField(blank=True, help_text='Crop photo (optional)', null=True, upload_to='crops/'),
        ),
    ]
