# Generated by Django 6.0.3 on 2026-04-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_animal_photo_alter_cropseason_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('well', 'Well'), ('river', 'River'), ('dam', 'Dam'), ('tank', 'Tank')], max_length=50)),
                ('total_capacity_liters', models.BigIntegerField()),
                ('current_level_liters', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='core.farm')),
            ],
            options={
                'db_table': 'feature_water_sources',
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('total_emissions_kg_co2e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fuel_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fertilizer_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_carbon_neutral', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_reports', to='core.farm')),
            ],
            options={
                'db_table': 'feature_carbon_reports',
                'unique_together': {('farm', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_documents', to='core.farm')),
                ('shared_with_users', models.ManyToManyField(blank=True, related_name='feature_shared_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_documents',
                'indexes': [models.Index(fields=['farm', 'expiry_date'], name='feature_doc_farm_id_b0f700_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('product_type', models.CharField(max_length=100)),
                ('production_start_date', models.DateField()),
                ('production_end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('a', 'Grade A'), ('b', 'Grade B'), ('c', 'Grade C')], default='a', max_length=20)),
                ('status', models.CharField(choices=[('produced', 'Produced'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='produced', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='core.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.field')),
            ],
            options={
                'db_table': 'feature_product_batches',
                'indexes': [models.Index(fields=['batch_id'], name='feature_pro_batch_i_2ef621_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reminder_type', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_reminders', to='core.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_reminders',
                'indexes': [models.Index(fields=['farm', 'due_date'], name='feature_rem_farm_id_1995a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('crop_yield', 'Crop Yield Report'), ('livestock_health', 'Livestock Health Report'), ('financial', 'Financial Report'), ('field_summary', 'Field Summary'), ('production', 'Production Report'), ('custom', 'Custom Report')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_reports', to='core.farm')),
            ],
            options={
                'db_table': 'feature_reports',
                'indexes': [models.Index(fields=['farm', 'report_type'], name='feature_rep_farm_id_a049ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('nitrogen_ppm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phosphorus_ppm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potassium_ppm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('organic_matter_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='core.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='core.field')),
            ],
            options={
                'db_table': 'feature_soil_tests',
                'indexes': [models.Index(fields=['field', 'test_date'], name='feature_soi_field_i_be9fda_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_tasks', to='core.farm')),
            ],
            options={
                'db_table': 'feature_tasks',
                'indexes': [models.Index(fields=['farm', 'due_date'], name='feature_tas_farm_id_80dadb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaterUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('usage_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('livestock', 'Livestock'), ('domestic', 'Domestic')], max_length=50)),
                ('liters_used', models.BigIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='core.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.field')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.watersource')),
            ],
            options={
                'db_table': 'feature_water_logs',
                'indexes': [models.Index(fields=['farm', 'usage_date'], name='feature_wat_farm_id_540e6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlertFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('frost', 'Frost'), ('heat', 'Excessive Heat'), ('drought', 'Drought'), ('flood', 'Flood'), ('wind', 'High Wind'), ('storm', 'Storm')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('alert_issued_at', models.DateTimeField()),
                ('alert_expires_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('recommended_actions', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_feature_alerts', to='core.farm')),
            ],
            options={
                'db_table': 'feature_weather_alerts_extended',
                'indexes': [models.Index(fields=['farm', 'alert_issued_at'], name='feature_wea_farm_id_ab76b3_idx')],
            },
        ),
    ]
