# Generated by Django 6.0.3 on 2026-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_groupbuyinginitiative_carbonsequestration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
