# Generated by Django 5.2.10 on 2026-04-10 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pestreport_analysis_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail Shop'), ('wholesale', 'Wholesale Distributor'), ('cooperative_shop', 'Cooperative Shop'), ('agro_dealer', 'Agro-Dealer'), ('hardware', 'Agricultural Hardware'), ('other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('physical_address', models.TextField()),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='supermarket/logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Store hours in JSON format: {"monday": "08:00-17:00", ...}')),
                ('products_categories', models.JSONField(blank=True, default=list, help_text='List of product categories they sell')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supermarkets',
            },
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, help_text='When marked out of stock: hidden from public marketplace but visible in seller dashboard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Smallholder Farmer'), ('large_farmer', 'Large Scale Farmer'), ('cooperative_admin', 'Cooperative Administrator'), ('agronomist', 'Agronomist/Extension Officer'), ('equipment_owner', 'Equipment Owner'), ('insurance_agent', 'Insurance Agent'), ('market_trader', 'Market Trader'), ('veterinarian', 'Veterinarian'), ('lab_technician', 'Soil Lab Technician'), ('supermarket', 'Supermarket/Agricultural Shop'), ('admin', 'System Administrator')], default='farmer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['seller', 'is_out_of_stock'], name='product_lis_seller__42fa66_idx'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['owner'], name='supermarket_owner_i_af1fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['is_verified'], name='supermarket_is_veri_a160b2_idx'),
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['is_active'], name='supermarket_is_acti_21c381_idx'),
        ),
    ]
