# Generated by Django 6.0.3 on 2026-04-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_supermarket_productlisting_is_out_of_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropseason',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('planting', 'Planting'), ('planted', 'Planted'), ('growing', 'Growing'), ('ready_for_harvest', 'Ready for Harvest'), ('harvested', 'Harvested'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='planned', max_length=20),
        ),
    ]
