# Generated by Django 5.2.10 on 2026-04-12 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cropseason_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('crop', '🌾 Crop Production'), ('livestock', '🐄 Livestock Production'), ('processing', '🏭 Agro-processing'), ('infrastructure', '🏗️ Farm Infrastructure'), ('soil', '🌱 Soil & Land Management'), ('pest', '🐛 Pest & Disease Management'), ('mechanization', '🚜 Farm Mechanization'), ('marketing', '📢 Marketing & Sales'), ('tourism', '🏕️ Farm Tourism'), ('sustainability', '🌍 Organic & Sustainability'), ('training', '📚 Training & Capacity Building'), ('financial', '💰 Financial & Business')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.CharField(choices=[('critical', '🔴 Critical'), ('high', '🟠 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('planning', '📋 Planning'), ('in_progress', '⚙️ In Progress'), ('on_hold', '⏸️ On Hold'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='planning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.farm')),
            ],
            options={
                'db_table': 'farm_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('achieved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.farmproject')),
            ],
            options={
                'db_table': 'project_milestones',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('labor', '👥 Labor'), ('equipment', '🚜 Equipment'), ('material', '📦 Material'), ('capital', '💰 Capital'), ('land', '🗺️ Land'), ('water', '💧 Water')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.farmproject')),
            ],
            options={
                'db_table': 'project_resources',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.farmproject')),
            ],
            options={
                'db_table': 'project_tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='farmproject',
            index=models.Index(fields=['farm', 'status'], name='farm_projec_farm_id_489592_idx'),
        ),
        migrations.AddIndex(
            model_name='farmproject',
            index=models.Index(fields=['category', 'priority'], name='farm_projec_categor_dafb24_idx'),
        ),
        migrations.AddIndex(
            model_name='farmproject',
            index=models.Index(fields=['target_end_date'], name='farm_projec_target__5be54e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'achieved'], name='project_mil_project_621806_idx'),
        ),
        migrations.AddIndex(
            model_name='projectresource',
            index=models.Index(fields=['project', 'resource_type'], name='project_res_project_cf186b_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'completed'], name='project_tas_project_5996e4_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_to', 'due_date'], name='project_tas_assigne_e43af6_idx'),
        ),
    ]
