# Generated by Django 5.2.16 on 2026-07-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_chatintent_chatresponse_chatstatistics_commodity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerlisting',
            old_name='inquiries',
            new_name='inquiry_count',
        ),
        migrations.AlterField(
            model_name='farmfield',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_fields', to='core.farm'),
        ),
        migrations.AlterField(
            model_name='farmlocation',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_location', to='core.farm'),
        ),
        migrations.AlterField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_fields', to='core.farm'),
        ),
    ]
