# Generated by Django 5.2.16 on 2026-07-16 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_inquiries_sellerlisting_inquiry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='deduction_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of deductions: {"tax": 100, "insurance": 50, "other": 20}'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workshift',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workshift',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hourly rate (usually 1.5x regular rate)', max_digits=8),
        ),
    ]
