# Generated by Django 5.2.16 on 2026-07-16 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_payroll_deduction_breakdown_payroll_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Overtime hourly rate (usually 1.5x regular rate)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='wage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
