# Generated by Django 5.2.16 on 2026-07-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_workshift_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
