# Generated by Django 5.2.16 on 2026-07-16 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_advisory_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredAdvisoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_type', models.CharField(choices=[('land_preparation', 'Land Preparation'), ('planting', 'Planting & Sowing'), ('crop_management', 'Crop Management'), ('pest_management', 'Pest Management'), ('harvest', 'Harvest & Post-Harvest'), ('livestock_feeding', 'Livestock Feeding'), ('livestock_health', 'Livestock Health'), ('livestock_breeding', 'Livestock Breeding'), ('irrigation', 'Irrigation & Water Management'), ('soil_management', 'Soil Management'), ('fertilizer', 'Fertilizer Application'), ('general', 'General Advisory')], max_length=30)),
                ('soil_type', models.CharField(blank=True, choices=[('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('clay', 'Clay Soil'), ('silty', 'Silty Soil'), ('peaty', 'Peaty Soil'), ('chalky', 'Chalky Soil')], max_length=20, null=True)),
                ('crop_type', models.CharField(blank=True, choices=[('maize', 'Maize'), ('wheat', 'Wheat'), ('sorghum', 'Sorghum'), ('millet', 'Millet'), ('rice', 'Rice'), ('soybeans', 'Soybeans'), ('groundnuts', 'Groundnuts'), ('beans', 'Beans'), ('tobacco', 'Tobacco'), ('cotton', 'Cotton'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=20, null=True)),
                ('livestock_type', models.CharField(blank=True, choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('poultry', 'Poultry'), ('rabbits', 'Rabbits'), ('other', 'Other')], max_length=20, null=True)),
                ('field_area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('irrigation_method', models.CharField(blank=True, choices=[('rainfed', 'Rainfed'), ('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler Irrigation'), ('flood', 'Flood Irrigation'), ('furrow', 'Furrow Irrigation'), ('center_pivot', 'Center Pivot')], max_length=30, null=True)),
                ('season', models.CharField(blank=True, choices=[('summer', 'Summer Season'), ('winter', 'Winter Season'), ('rainy', 'Rainy Season'), ('dry', 'Dry Season')], max_length=20, null=True)),
                ('specific_question', models.TextField(help_text='Describe your specific question or problem')),
                ('current_practices', models.TextField(blank=True, help_text='Describe your current practices')),
                ('challenges', models.TextField(blank=True, help_text="Describe any challenges you're facing")),
                ('ai_response', models.TextField(blank=True)),
                ('response_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_advisory_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Structured Advisory Request',
                'verbose_name_plural': 'Structured Advisory Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
