# Generated by Django 5.2.16 on 2026-07-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_structuredadvisoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredadvisoryrequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for better analysis (e.g., crop, pest, soil, livestock)', null=True, upload_to='advisory_images/'),
        ),
    ]
