# Generated by Django 5.2.16 on 2026-07-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_structuredadvisoryrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldprediction',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_predictions', to='core.cropseason'),
        ),
        migrations.AlterField(
            model_name='yieldprediction',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_predictions', to='core.farm'),
        ),
        migrations.AlterField(
            model_name='yieldprediction',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yield_predictions', to='core.field'),
        ),
    ]
