# Generated by Django 5.2.16 on 2026-07-18 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_equipment_latitude_equipment_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('planter', 'Planter'), ('sprayer', 'Sprayer'), ('plow', 'Plow'), ('cultivator', 'Cultivator'), ('trailer', 'Trailer'), ('irrigation', 'Irrigation Equipment'), ('vehicle', 'Vehicle'), ('tool', 'Tool'), ('machinery', 'Machinery'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('repair', 'Needs Repair'), ('sale', 'For Sale'), ('retired', 'Retired'), ('lost', 'Lost')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['owner', 'status'], name='assets_owner_i_396750_idx'), models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'), models.Index(fields=['next_maintenance_date'], name='assets_next_ma_992b64_idx')],
            },
        ),
    ]
