# Generated by Django 5.2.16 on 2026-07-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('farmer_notes', models.TextField(blank=True, help_text='Additional notes from farmer')),
                ('agronomist_response', models.TextField(blank=True, help_text='Response from agronomist')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('agronomist', models.ForeignKey(limit_choices_to={'user_type': 'agronomist'}, on_delete=django.db.models.deletion.CASCADE, related_name='pest_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('pest_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='core.pestreport')),
            ],
            options={
                'db_table': 'pest_verification_requests',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['pest_report', 'status'], name='pest_verifi_pest_re_35bf55_idx'), models.Index(fields=['agronomist', 'status'], name='pest_verifi_agronom_b86eba_idx'), models.Index(fields=['sent_at'], name='pest_verifi_sent_at_97550b_idx')],
            },
        ),
    ]
