# Generated by Django 5.2.16 on 2026-07-22 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_pestverificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('tools', 'Tools & Equipment'), ('feed', 'Animal Feed'), ('medicine', 'Veterinary Medicine'), ('fuel', 'Fuel & Lubricants'), ('spare_parts', 'Spare Parts'), ('packaging', 'Packaging Materials'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('pieces', 'Pieces'), ('bags', 'Bags'), ('boxes', 'Boxes'), ('tons', 'Tons'), ('units', 'Units')], max_length=20)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='Storage location', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired')], default='in_stock', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.farm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'category'], name='inventory_owner_i_957b3b_idx'), models.Index(fields=['status'], name='inventory_status_2fc879_idx'), models.Index(fields=['expiry_date'], name='inventory_expiry__6e8fe4_idx')],
            },
        ),
    ]
