# Generated by Django 5.2.16 on 2026-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='animals',
            field=models.ManyToManyField(blank=True, help_text='Animals this inventory is used for', related_name='inventory_items', to='core.animal'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='crop_seasons',
            field=models.ManyToManyField(blank=True, help_text='Crops this inventory is used for', related_name='inventory_items', to='core.cropseason'),
        ),
    ]
