# Generated by Django 5.2.16 on 2026-07-22 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_inventory_animals_inventory_crop_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('water_type', models.CharField(choices=[('freshwater', 'Freshwater'), ('brackish', 'Brackish Water'), ('marine', 'Marine/Saltwater')], default='freshwater', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('growth_period_days', models.IntegerField(help_text='Average days to reach market size')),
                ('ideal_temperature_min', models.DecimalField(decimal_places=2, help_text='Min temperature in Celsius', max_digits=5)),
                ('ideal_temperature_max', models.DecimalField(decimal_places=2, help_text='Max temperature in Celsius', max_digits=5)),
                ('market_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fish_species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FishPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pond_type', models.CharField(choices=[('earthen', 'Earthen Pond'), ('concrete', 'Concrete Pond'), ('plastic', 'Plastic Tank'), ('fiber', 'Fiber Tank'), ('cage', 'Floating Cage'), ('raceway', 'Raceway')], max_length=20)),
                ('length_m', models.DecimalField(decimal_places=2, help_text='Length in meters', max_digits=10)),
                ('width_m', models.DecimalField(decimal_places=2, help_text='Width in meters', max_digits=10)),
                ('depth_m', models.DecimalField(decimal_places=2, help_text='Depth in meters', max_digits=10)),
                ('volume_cubic_meters', models.DecimalField(decimal_places=2, help_text='Volume in cubic meters', max_digits=10)),
                ('max_stocking_density', models.IntegerField(help_text='Max fish per cubic meter')),
                ('location', models.CharField(blank=True, help_text='Physical location on farm', max_length=255)),
                ('water_source', models.CharField(blank=True, help_text='Source of water (borehole, river, etc.)', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('drained', 'Drained')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_ponds', to='core.farm')),
            ],
            options={
                'db_table': 'fish_ponds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FishCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Spring Season'), ('summer', 'Summer Season'), ('autumn', 'Autumn Season'), ('winter', 'Winter Season'), ('rainy', 'Rainy Season'), ('dry', 'Dry Season'), ('custom', 'Custom Season')], max_length=20)),
                ('cycle_name', models.CharField(blank=True, help_text='Optional name for this cycle', max_length=255)),
                ('stocking_date', models.DateField()),
                ('stock_quantity', models.IntegerField(help_text='Number of fish stocked')),
                ('average_weight_at_stocking_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_harvest_date', models.DateField()),
                ('expected_weight_per_fish_g', models.DecimalField(decimal_places=2, help_text='Expected weight per fish in grams', max_digits=8)),
                ('expected_survival_rate', models.DecimalField(decimal_places=2, default=80, help_text='Expected survival rate percentage', max_digits=5)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_quantity', models.IntegerField(blank=True, help_text='Actual number harvested', null=True)),
                ('average_weight_at_harvest_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('stocking', 'Stocking'), ('growing', 'Growing'), ('feeding', 'Feeding'), ('ready_for_harvest', 'Ready for Harvest'), ('harvested', 'Harvested'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='planned', max_length=20)),
                ('seed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('feed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fish_cycles', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='core.fishpond')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='core.fishspecies')),
            ],
            options={
                'db_table': 'fish_cycles',
                'ordering': ['-stocking_date'],
            },
        ),
        migrations.CreateModel(
            name='FishProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.IntegerField(help_text='Number of fish harvested')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, help_text='Total weight in kg', max_digits=10)),
                ('average_weight_g', models.DecimalField(decimal_places=2, help_text='Average weight per fish in grams', max_digits=8)),
                ('grade', models.CharField(blank=True, help_text='Grade/quality of fish', max_length=50)),
                ('sold_quantity', models.IntegerField(blank=True, help_text='Number of fish sold', null=True)),
                ('sold_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_quantity', models.IntegerField(blank=True, help_text='Fish kept for breeding or other purposes', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='core.fishcycle')),
            ],
            options={
                'db_table': 'fish_production',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AddIndex(
            model_name='fishcycle',
            index=models.Index(fields=['pond', 'status'], name='fish_cycles_pond_id_d3b7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='fishcycle',
            index=models.Index(fields=['stocking_date'], name='fish_cycles_stockin_e867c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fishcycle',
            index=models.Index(fields=['expected_harvest_date'], name='fish_cycles_expecte_8578b7_idx'),
        ),
    ]
