# Generated by Django 5.2.16 on 2026-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_fishspecies_fishpond_fishcycle_fishproduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fish_cycles',
            field=models.ManyToManyField(blank=True, help_text='Fish farming cycles this inventory is used for', related_name='inventory_items', to='core.fishcycle'),
        ),
    ]
