# Generated by Django 5.2.16 on 2026-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_inventory_fish_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropseason',
            name='area_allocated_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area allocated for this crop (in hectares)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='suitable_seasons',
            field=models.JSONField(default=list, help_text="List of suitable seasons (e.g., ['main', 'long_rain'])"),
        ),
    ]
