# Generated by Django 5.2.16 on 2026-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cropseason_area_allocated_hectares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropseason',
            name='season',
            field=models.CharField(choices=[('main_rainy', 'Main Rainy Season (Nov-Mar)'), ('early_planting', 'Early Planting (Sept-Oct)'), ('late_planting', 'Late Planting (Dec-Jan)'), ('winter', 'Winter Season (Apr-Aug)'), ('irrigated', 'Irrigated/Off-Season'), ('short_rain', 'Short Rain Season')], max_length=20),
        ),
    ]
