# Generated by Django 5.2.16 on 2026-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_cropseason_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpond',
            name='volume_cubic_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume in cubic meters (auto-calculated)', max_digits=10, null=True),
        ),
    ]
