# Generated by Django 5.2.16 on 2026-07-22 14:49

from django.db import migrations


def add_fish_species(apps, schema_editor):
    FishSpecies = apps.get_model('core', 'FishSpecies')
    
    species_data = [
        {
            'name': 'Tilapia',
            'scientific_name': 'Oreochromis niloticus',
            'water_type': 'freshwater',
            'description': 'Most popular fish for aquaculture in Zimbabwe. Fast-growing, hardy, and adaptable to various conditions.',
            'growth_period_days': 180,
            'ideal_temperature_min': 25,
            'ideal_temperature_max': 30,
            'market_price_per_kg': 5.00,
        },
        {
            'name': 'Catfish',
            'scientific_name': 'Clarias gariepinus',
            'water_type': 'freshwater',
            'description': 'African catfish, fast-growing and tolerant of poor water conditions. Can be farmed in high density.',
            'growth_period_days': 210,
            'ideal_temperature_min': 20,
            'ideal_temperature_max': 28,
            'market_price_per_kg': 6.00,
        },
        {
            'name': 'Rainbow Trout',
            'scientific_name': 'Oncorhynchus mykiss',
            'water_type': 'freshwater',
            'description': 'Cold-water fish suitable for high-altitude areas in Zimbabwe. Requires good water quality and oxygen.',
            'growth_period_days': 240,
            'ideal_temperature_min': 12,
            'ideal_temperature_max': 18,
            'market_price_per_kg': 12.00,
        },
        {
            'name': 'Common Carp',
            'scientific_name': 'Cyprinus carpio',
            'water_type': 'freshwater',
            'description': 'Hardy fish that grows well in various conditions. Good for polyculture systems.',
            'growth_period_days': 270,
            'ideal_temperature_min': 20,
            'ideal_temperature_max': 28,
            'market_price_per_kg': 4.50,
        },
        {
            'name': 'Bream',
            'scientific_name': 'Oreochromis mossambicus',
            'water_type': 'freshwater',
            'description': 'Mozambique tilapia, well-adapted to Zimbabwean conditions. Good for both small and large-scale farming.',
            'growth_period_days': 200,
            'ideal_temperature_min': 22,
            'ideal_temperature_max': 30,
            'market_price_per_kg': 5.50,
        },
    ]
    
    for species in species_data:
        FishSpecies.objects.create(**species)


def remove_fish_species(apps, schema_editor):
    FishSpecies = apps.get_model('core', 'FishSpecies')
    FishSpecies.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_fishpond_volume_cubic_meters'),
    ]

    operations = [
        migrations.RunPython(add_fish_species, remove_fish_species),
    ]
