# Generated by Django 5.2.16 on 2026-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20260722_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcycle',
            name='seed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fingerling/Startup Cost'),
        ),
    ]
